# Autogenerated wrapper script for pixi_jll for x86_64-w64-mingw32
export pixi

JLLWrappers.@generate_wrapper_header("pixi")
JLLWrappers.@declare_executable_product(pixi)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        pixi,
        "bin\\pixi.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
